title = "DEXON Consensus Simulation Config"

[node]
num = 21
propose_interval_mean = 5e+02
propose_interval_sigma = 5e+0
max_block = 20

[node.consensus]
phi_ratio = 6.66670024394989e-01
k = 1

[networking]
type = "tcp-local"
peer_server = "peer.server"
mean = 1e+02
sigma = 1e+01
loss_rate_value = 0e+00
