title = "DEXON Consensus Simulation Config"

[node]
num = 7
max_block = 18446744073709551615

# node.consensus is the genesis configuration.
[node.consensus]
genesis_crs = "In DEXON we trust."
lambda_ba = 250
lambda_dkg = 4000
round_interval = 1000
notary_set_size = 7
dkg_set_size = 7
min_block_interval = 750

# node.config_changes describe the changes of configuration for each round.
[[node.changes]]
round = 1
type = "notary_set_size"
value = "5"
[[node.changes]]
round = 2
type = "notary_set_size"
value = "6"
[[node.changes]]
round = 3
type = "notary_set_size"
value = "4"

[node.legacy]
propose_interval_mean = 5e+02
propose_interval_sigma = 5e+01

[networking]
type = "fake"
peer_server = "127.0.0.1"
[networking.direct]
mean = 1e+01
sigma = 1e+01
[networking.gossip]
mean = 3e+01
sigma = 3e+01

[scheduler]
worker_num = 2
