apiVersion: v1
kind: Service
metadata:
  name: peer-server-svc
  labels:
    app: peer-server-svc
spec:
  selector:
    app: dexcon-simulation-peer-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dexcon-simulation-peer-server
  labels:
    app: dexcon-simulation-peer-server
spec:
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      name: dexcon-simulation-peer-server
      labels:
        app: dexcon-simulation-peer-server
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
      containers:
        - name: dexcon-simulation
          image: asia.gcr.io/cobinhood/dexcon-simulation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 4
              memory: 4Gi
            limits:
              cpu: 4
              memory: 4Gi
          env:
            - name: ROLE
              value: "peer-server"
